/**
 * Writes the standalone brand assets into /brand from the single source of
 * truth in lib/brand.ts, plus the site's favicon into /site/public. Same
 * philosophy as the card export: one definition in the codebase, and the
 * outside world gets files.
 *
 *   node scripts/export-brand.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import puppeteer from "puppeteer";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../..");
const out = path.join(root, "brand");

// lib/brand.ts is plain data with no imports, so it can be read and evaluated
// without a bundler. Strip the types and take the values.
const src = fs.readFileSync(path.join(here, "../lib/brand.ts"), "utf8");
const pick = (name) => {
  const m = src.match(new RegExp(`export const ${name}[^=]*=\\s*([\\s\\S]*?);\\n`, "m"));
  if (!m) throw new Error(`could not read ${name} from lib/brand.ts`);
  // `as const` is TypeScript; strip it before evaluating the literal.
  return eval(`(${m[1].replace(/\s+as const$/, "")})`);
};

const MARK_VIEWBOX = pick("MARK_VIEWBOX");
const GLYPH_VIEWBOX = pick("GLYPH_VIEWBOX");
const DISC_PATH = pick("DISC_PATH");
const RING_PATH = pick("RING_PATH");
const RING_STROKE_WIDTH = pick("RING_STROKE_WIDTH");
const WAVE_PATHS = pick("WAVE_PATHS");
const PALETTE = pick("PALETTE");

const head = (viewBox, label) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" role="img" aria-label="${label}">\n` +
  `  <!-- Vibe Corp. Generated by card-studio/scripts/export-brand.mjs — do not hand-edit. -->\n`;

const waves = (fill, indent = "  ") =>
  `${indent}<g id="waves" fill="${fill}">\n` +
  WAVE_PATHS.map((d) => `${indent}  <path d="${d}"/>`).join("\n") +
  `\n${indent}</g>\n`;

const ring = (stroke) =>
  `  <path id="ring" fill="none" stroke="${stroke}" stroke-width="${RING_STROKE_WIDTH}" stroke-miterlimit="10" d="${RING_PATH}"/>\n`;

const files = {
  // The atomic form. currentColor so it takes the colour of its context.
  "mark/glyph.svg": head(GLYPH_VIEWBOX, "Vibe Corp") + waves("currentColor") + "</svg>\n",

  // Primary mark, context-coloured.
  "mark/badge.svg":
    head(MARK_VIEWBOX, "Vibe Corp") +
    `  <path id="disc" fill="${PALETTE.ink.hex}" d="${DISC_PATH}"/>\n` +
    ring("currentColor") +
    waves("currentColor") +
    "</svg>\n",

  // Fully-specified cream-on-ink, for anywhere currentColor will not reach
  // (email, a print RIP, a vendor's upload form).
  "mark/badge-cream.svg":
    head(MARK_VIEWBOX, "Vibe Corp") +
    `  <path id="disc" fill="${PALETTE.ink.hex}" d="${DISC_PATH}"/>\n` +
    ring(PALETTE.cream.hex) +
    waves(PALETTE.cream.hex) +
    "</svg>\n",

  // One colour, no disc — vinyl, embroidery, foil, a rubber stamp.
  "mark/badge-mono.svg":
    head(MARK_VIEWBOX, "Vibe Corp") + ring("currentColor") + waves("currentColor") + "</svg>\n",

  // Small sizes: the ring fills in below ~24px, so it is simply not there.
  "mark/badge-small.svg":
    head(MARK_VIEWBOX, "Vibe Corp") +
    `  <path id="disc" fill="${PALETTE.ink.hex}" d="${DISC_PATH}"/>\n` +
    waves("currentColor") +
    "</svg>\n",
};

// Design tokens, for anything that is not React.
const tokens =
  `/* Vibe Corp brand tokens. Generated — do not hand-edit.\n` +
  `   Source: card-studio/lib/brand.ts */\n:root {\n` +
  Object.entries(PALETTE)
    .map(([k, v]) => `  --vc-${k}: ${v.hex}; /* ${v.role} */`)
    .join("\n") +
  `\n}\n`;

fs.mkdirSync(path.join(out, "mark"), { recursive: true });
for (const [rel, body] of Object.entries(files)) {
  fs.writeFileSync(path.join(out, rel), body);
  console.log("wrote brand/" + rel);
}

// The site's favicon is the glyph, fully specified — a browser tab gives
// currentColor nothing to inherit. Mustard, because it holds on light and dark
// tab bars alike. Written to site/public/, which Vite serves verbatim at /.
const site = path.join(root, "site", "public");
const favicon = head(GLYPH_VIEWBOX, "Vibe Corp") + waves(PALETTE.mustard.hex) + "</svg>\n";
fs.writeFileSync(path.join(site, "favicon.svg"), favicon);
console.log("wrote site/public/favicon.svg");

// iOS home-screen icon: opaque, so the glyph sits on the site's black ground
// with room around it for the rounded mask.
const TOUCH_PX = 180;
const browser = await puppeteer.launch({ headless: true });
try {
  const page = await browser.newPage();
  await page.setViewport({ width: TOUCH_PX, height: TOUCH_PX, deviceScaleFactor: 1 });
  await page.setContent(
    `<body style="margin:0;width:${TOUCH_PX}px;height:${TOUCH_PX}px;background:${PALETTE.black.hex};` +
      `display:grid;place-items:center">` +
      favicon.replace("<svg ", `<svg width="${TOUCH_PX * 0.62}" height="${TOUCH_PX * 0.62}" `) +
      `</body>`,
  );
  await page.screenshot({ path: path.join(site, "apple-touch-icon.png") });
  console.log("wrote site/public/apple-touch-icon.png");
} finally {
  await browser.close();
}
fs.writeFileSync(path.join(out, "tokens.css"), tokens);
console.log("wrote brand/tokens.css");
fs.writeFileSync(
  path.join(out, "tokens.json"),
  JSON.stringify({ palette: PALETTE }, null, 2) + "\n",
);
console.log("wrote brand/tokens.json");
