/**
 * VIBE CORP — brand root.
 *
 * The single source of truth for the mark, the palette and the type scale.
 * Everything downstream reads from here: the React components in
 * components/brand, the standalone SVGs in /brand (generated by
 * scripts/export-brand.mjs), and eventually the site.
 *
 * The mark is drawn on a 150x150 canvas. It is NOT geometrically perfect —
 * the disc and the inner ring are both slightly irregular, hand-drawn circles,
 * and the whole mark sits about one unit high of centre. That is deliberate
 * and preserved: Vibe Corp is old and accreted, and a mark struck by hand a
 * long time ago should not measure like one struck by a machine. Do not
 * "correct" these paths to true circles.
 */

export const MARK_VIEWBOX = "0 0 150 150";

/** Optical centre of the mark — the disc, ring and waves all agree on this,
 *  and it is NOT (75, 75). Anything concentric with the mark uses this. */
export const MARK_CENTER = { x: 75, y: 74.2 } as const;

/** The outer disc — the black ground the mark is struck into. */
export const DISC_PATH =
  "m143.8 73c-0.5-25.1-15.3-43.2-27.5-52-10.2-7.3-22.3-13-37.2-13.7h-6.1c-13.4 0.3-24.2 4.2-32.9 9.5-8.6 5.3-16.5 12.7-22.3 21.5-5.5 8.5-9.8 18.4-10.8 30.2-0.2 1.8-0.2 3.5-0.4 4.9v3.5c0.4 16 6.1 27.8 12.8 36.9 3.6 4.9 8.4 9.8 14 13.9 10.2 7.3 22.6 13.7 39.3 14.7h3.8c13.8-0.3 24.5-3.7 33.1-8.5 4.6-2.5 8.7-5.4 12.3-8.6l3.9-3.8c8.7-9.4 16-21.8 17.8-38.5 0.2-2 0.4-4 0.4-6.1v-3.9h-0.2z";

/** The inner hairline ring. Stroked, never filled. */
export const RING_PATH =
  "m73.1 25.1c-22.4 0.6-40.6 17.7-46.2 38.4-0.9 4.3-0.9 8.5-0.7 12.8 1.1 18.9 13.9 36.6 33.2 43.3 4.6 1.4 9 2.4 14 2.7 21.2 0.7 38.6-11.1 45.9-27.6 2.6-5.7 4.3-12.4 4.5-19.9 0-20.9-12-36.7-28.2-44.6-5.3-2.7-12.8-5.3-22.5-5.1z";

export const RING_STROKE_WIDTH = 1.7498;

/** The three waves — the glyph proper. Top to bottom. */
export const WAVE_PATHS = [
  "m68.7 34.9c-9.4 0-17.2 5-22.7 11.3-3.8 4.6-8.4 11.7-10.6 20.3-0.4 4 2.4 0.1 7.1-4 3.1-2.7 7.8-5.9 10.2-7.1 3.9-2.1 7.3-3.8 12.9-3.9 5 0.1 10.3 2.1 15.4 8.6 3 4 5.2 6.5 9.3 9 3.7 2.3 7.4 3.6 12.3 2.6 5.2-1.1 9.6-4.4 13.2-7.6 0.5-0.4 0.4-1.1-0.1-4.1-0.5-2.4-0.8-1.8-2.1-1.1-1.7 0.9-3.4 2.2-7.5 2.1-2.1-0.1-5-1.1-7.3-3.4-3.4-3.4-6.2-9.7-10.4-14-4.1-4.4-10-8.5-18.7-8.7h-1z",
  "m61.5 59.2c-6.9 0-13.5 4.1-18.7 8.8-3.1 2.9-4.5 3.9-7.6 5.9-0.7 0.5-0.8 0.6-0.6 4.1 0.3 3.8 0.7 2.2 5.1-1.1 5-3.8 10.2-7.8 18.5-7.9 3.4 0 7.2 1 10.9 3.3 4 2.6 6.3 5.8 8 7.6 3.9 3.9 8.4 6.7 14.4 7h1.6c7.3-0.3 12.3-2.9 18.8-8 3-2.4 4.6-2.8 5.1-3.4 0.3-0.4 0.3-3.9 0-6.2-0.4-1.8-1.9 0.2-4.2 1.9-4 2.9-8.8 6.3-16.3 6.4-4.4 0-10.3-1.5-16-7.3-2.9-3-7.8-10.3-18.3-11.1h-0.7z",
  "m55.4 75.1c-6.2 0.1-10.3 3.2-14 6.2-4 3.1-5.5 4.1-5.7 4.2s-0.1 1.5 0.7 3.9c0.7 1.9 1.2 0.7 3.9-0.5 2.2-1.2 5.4-2.4 8.1-1.8 5.8 1.4 8 5 12.2 11.2 1.8 2.5 4 5.2 6 7.1 5.2 4.7 10.5 7.7 18.3 7.8 5.1-0.1 10.7-1.7 15-4.1 5.9-3.4 10.2-8.5 12.2-12.2 2.4-4 4.2-8.5 4.6-13.1 0.2-3.2-1.5-1.9-4.3 1.1-4 3.5-11 9-20.3 9.3h-1.4c-8.3 0-14-3.6-18.7-9.4-3.9-4.6-7.8-9.3-15.6-9.7h-1z",
];

/** Tight square viewBox around the waves alone, for the bare glyph.
 *  Measured, not guessed: the waves occupy 34.51,34.9 to 117.23,113.2. */
export const GLYPH_VIEWBOX = "32.9 31.1 86 86";

/**
 * The waves' own bounding box, measured in a browser with getBBox — not
 * derived from the 150 grid and not eyeballed.
 *
 * THIS IS NOT THE CANVAS CENTRE. The artwork centres at (75.87, 74.05), while
 * the canvas centres at (75, 75) and the disc and ring centre at MARK_CENTER.
 * Placing the waves on any of the other three leaves them visibly off-centre
 * inside a ring — which is exactly the bug this constant exists to prevent.
 * Anything that centres the waves in something must use GLYPH_CENTER.
 */
export const GLYPH_BBOX = { x: 34.51, y: 34.9, w: 82.72, h: 78.3 } as const;
export const GLYPH_CENTER = {
  x: GLYPH_BBOX.x + GLYPH_BBOX.w / 2, // 75.87
  y: GLYPH_BBOX.y + GLYPH_BBOX.h / 2, // 74.05
} as const;

/* -------------------------------------------------------------------------
 * RING TYPE GEOMETRY
 *
 * Setting two lines of type around a circle has two traps in it. Both were
 * found the hard way, and both are encoded here so nothing has to find them
 * again.
 * ---------------------------------------------------------------------- */

/** Cap height as a fraction of font size. Close enough across the grotesques
 *  we set ring type in, and the only number the baseline maths needs. */
export const CAP_RATIO = 0.72;

/**
 * TRAP 1 — the two lines do not sit on the same radius.
 *
 * Glyphs on a top arc grow OUTWARD from their baseline; glyphs on a bottom arc
 * grow INWARD. So two lines sharing one radius occupy two different bands, the
 * top one a whole cap height further out than the bottom. It reads as subtly
 * wrong with no obvious culprit.
 *
 * The fix: pick the radius of the BAND you want the type to fill, then push
 * each baseline half a cap height the other way. Both lines then sit centred
 * in that one band.
 */
export function ringTypeBaseline(bandRadius: number, fontSize: number, place: "top" | "bottom") {
  const half = (fontSize * CAP_RATIO) / 2;
  return place === "top" ? bandRadius - half : bandRadius + half;
}

/**
 * The half-circle a line of ring type runs along. Both arcs travel LEFT to
 * RIGHT so both lines read clockwise the way a struck seal does: the top one
 * over the top (sweep 1, heads pointing out), the bottom one under the bottom
 * (sweep 0, heads pointing back in toward the middle).
 */
export function ringTypeArc(cx: number, cy: number, radius: number, place: "top" | "bottom") {
  const sweep = place === "top" ? 1 : 0;
  return `M ${cx - radius} ${cy} A ${radius} ${radius} 0 0 ${sweep} ${cx + radius} ${cy}`;
}

/**
 * TRAP 3 — the two lines need DIFFERENT tracking to look equally tracked.
 *
 * Letter-spacing is a distance along the BASELINE, and the two baselines sit on
 * different radii (that is trap 1). The same spacing therefore subtends a
 * bigger angle on the tighter top arc than on the wider bottom one.
 *
 * What the eye actually reads is not the gap at the baseline but the gap
 * through the middle of the letters — and because the glyphs stand radially,
 * gaps FAN OPEN with height on the top arc and PINCH SHUT on the bottom one.
 * Measured at mid-cap (which is the band radius for both lines), the gap comes
 * out as `track * band / baseline`. Top is looser, bottom is tighter, and the
 * two words look like they were set by different people.
 *
 * Dividing that back out gives both lines the same optical rhythm: the top
 * line's tracking is reduced and the bottom line's increased, by exactly the
 * ratio of its baseline to the band.
 */
export function ringTypeTracking(
  bandRadius: number,
  fontSize: number,
  place: "top" | "bottom",
  tracking: number,
) {
  return fontSize * tracking * (ringTypeBaseline(bandRadius, fontSize, place) / bandRadius);
}

/**
 * TRAP 2 — the correction that is NOT needed. Recorded because it is the
 * obvious next move and it is wrong.
 *
 * SVG letter-spacing adds a space after the LAST glyph as well, so it looks as
 * though `text-anchor: middle` must be centring an advance one space too wide,
 * leaving the ink half a space to the left — and as though startOffset should
 * add half a track back.
 *
 * Measured in Chrome on a 200-unit box: plain `startOffset="50%"` lands the ink
 * at 100.2, and adding the half-track correction moves it to 101.8. The engine
 * has already handled it. Always set startOffset to "50%" and leave it alone.
 */
export const RING_TYPE_START_OFFSET = "50%";

/**
 * THE STAMP — locked.
 *
 * The "Vibes Certified" seal, in mark units on its own 200-unit box (the stamp
 * is not drawn on the 150 grid the badge uses; it is its own construction).
 *
 * These proportions are the end of a deliberate sequence. The ratio that
 * governs the whole thing is the depth of the type band against the width of
 * the centre: it began at 9.7 against 79, which read as a caption wrapped
 * around a logo, and finished at 15.5 against 64, where the ring leads and the
 * waves sit inside it as the quiet centre. Moving `size` without moving
 * `band`, `innerRule` and `waveWidth` with it will undo that.
 */
export const STAMP = {
  /** The stamp's own square canvas, and its centre. */
  viewBox: "0 0 200 200",
  center: 100,
  /** Heavy outer rule. */
  ruleRadius: 96,
  ruleWidth: 5,
  /** The bead ring — borrowed from the notarial direction. At size the eye
   *  reads the BAND, not the individual beads, which is what makes the stamp
   *  look struck rather than drawn. */
  beadRadius: 85,
  beadCount: 60,
  beadSize: 2.1,
  /** Light inner rule. Without beads this closes up — see STAMP_PLAIN.
   *  The width is set by the RUBBER, not by taste: see STAMP_DIE_MM below. */
  innerRule: 76,
  innerRuleWidth: 2.2,
  /** The band the two words fill, and what fills it. */
  band: 59,
  fontSize: 23.5,
  tracking: 0.18,
  starSize: 22,
  /** Width of the waves across the middle. */
  waveWidth: 62,
} as const;

/**
 * The physical die this stamp is cut for: a Trodat 4630 / 46030, 30mm round.
 *
 * That number is a real constraint, not a note. At 30mm the 200-unit box makes
 * ONE UNIT = 0.15mm, and a polymer stamp die will not reliably hold a line
 * under about 0.3mm — it fills in with ink, or crumbles. So:
 *
 *   ruleWidth      5    = 0.75mm  fine
 *   innerRuleWidth 2.2  = 0.33mm  just over the floor (was 1.8 = 0.27mm, under it)
 *   beadSize       2.1r = 0.63mm  fine, with 0.7mm gaps between beads
 *   fontSize       23.5 = 2.54mm cap height, about 7pt
 *
 * Anything here that shrinks must be re-checked against MIN_STROKE_MM before
 * it goes to a stamp maker.
 */
export const STAMP_DIE_MM = 30;
export const STAMP_UNIT_MM = STAMP_DIE_MM / 200;
export const MIN_STROKE_MM = 0.3;

/**
 * The same stamp without the bead ring. Not just STAMP with beads switched off:
 * an empty 20-unit band between the rules reads as a missing element, so the
 * rules close from 20 apart to 8 and everything inside moves out into the room
 * the beads were using.
 */
export const STAMP_PLAIN = {
  ...STAMP,
  innerRule: 88,
  band: 68,
  waveWidth: 80,
} as const;

/** Smallest the stamp survives, measured off the render rather than hoped for:
 *  below this the beads close up and the longer word fills in. Under it, use
 *  the bare glyph — never a shrunk stamp. */
export const STAMP_MIN_PX = 64;
export const STAMP_PLAIN_MIN_PX = 48;

/**
 * PALETTE.
 *
 * Lifted out of the deck, where it was already locked, and given roles. The
 * hex values are unchanged — the cards, the back and the stickers must be the
 * same outfit.
 *
 * `signal` is the one that matters: mustard is Vibe Corp's single signal
 * colour. It marks the thing you are meant to read. Everything else is ground,
 * ink, or band.
 */
export const PALETTE = {
  // Grounds — what brand surfaces sit on.
  black: { hex: "#000000", role: "Deep ground. Cosmic backdrop, sticker die-cut ground." },
  ink: { hex: "#0b0b0c", role: "The disc. Near-black with a hint of warmth." },
  plum: { hex: "#251435", role: "The working ground. Plates, panels, page." },
  // Ink — what sits on the grounds.
  cream: { hex: "#f3e9d6", role: "Body ink on dark. Never pure white." },
  // Signal — the one colour that means 'read this'.
  mustard: { hex: "#e8a929", role: "SIGNAL. Rules, borders, the one true line, the seal's type." },
  // Bands — the wave pattern and illustration. Never used for type.
  teal: { hex: "#2fa090", role: "Band." },
  blue: { hex: "#3358c4", role: "Band." },
  purple: { hex: "#a274d6", role: "Band. Also the uniform — crew hi-vis." },
  rose: { hex: "#dd8296", role: "Band." },
  brick: { hex: "#c4462a", role: "Band." },
} as const;

export type PaletteKey = keyof typeof PALETTE;

export const BAND_KEYS: PaletteKey[] = ["teal", "mustard", "brick", "rose", "purple", "blue"];

/** The gradient treatment — teal to blue to rose, the sweep on the card back.
 *  A TREATMENT, not the mark. The flat mark is canonical. */
export const GRADIENT_STOPS = [
  { offset: "0%", color: PALETTE.teal.hex },
  { offset: "45%", color: PALETTE.blue.hex },
  { offset: "100%", color: PALETTE.rose.hex },
];

/**
 * TYPE — three voices, no more.
 *
 * Already true on the cards; named here so it holds off them too.
 *  PLATE   uppercase, heavily letterspaced sans. Names, labels, headings.
 *  CODE    mono. Classification codes, URLs, anything machine-issued.
 *  TRUE    ornate serif. The one line per surface that is the point.
 */
export const TYPE_VOICES = [
  {
    key: "plate",
    name: "Plate",
    use: "Names, designations, labels, headings, the seal's ring type.",
    css: "uppercase, tracking 0.16–0.2em, semibold",
  },
  {
    key: "code",
    name: "Code",
    use: "Classification codes, URLs, section labels. Anything issued by the Grid rather than written by a person.",
    css: "mono, uppercase, tracking 0.2–0.42em",
  },
  {
    key: "true",
    name: "True",
    use: "The one serif line per surface. Taglines, assignments. Never more than one voice-of-truth block.",
    css: "serif, often uppercase with tracking 0.09em",
  },
] as const;

/**
 * THE EMBLEM — the round VIBE / CORP mark, as distinct from the STAMP.
 *
 * Same 200-unit box as the stamp and the same ring-type rules, but no beads and
 * no bottom label: two four-letter words, a star closing each shoulder, and the
 * glyph in the middle. Four letters fill about half their arc where CERTIFIED
 * filled three quarters, which is why the type here is 29 against the stamp's
 * 23.5 — short words need bigger type to keep the ring from going slack.
 */
export const EMBLEM = {
  viewBox: "0 0 200 200",
  center: 100,
  ruleRadius: 96,
  ruleWidth: 5,
  innerRule: 88,
  innerRuleWidth: 1.8,
  band: 67,
  fontSize: 29,
  tracking: 0.22,
  starSize: 25,
  waveWidth: 76,
} as const;

/**
 * STICKER — the emblem cut as a circle.
 *
 * The purple is a deliberate step up from the plum ground: lighter, but not as
 * light as the palette's own `purple`, which drops cream to 2.9:1 and washes
 * the hairline rules out. This sits at 7.1:1, which the 1.8-unit inner rule
 * still survives. Measured, not chosen by eye.
 *
 * BLEED and SAFE are the trade's usual eighth of an inch. The emblem's outer
 * rule sits exactly on the safe circle — as far out as it can go and still
 * survive a die that wanders the full tolerance.
 */
export const STICKER = {
  ground: "#5c3d82",
  ink: PALETTE.cream.hex,
  bleedMm: 3.175,
  safeMm: 3.175,
  /** Diameters worth ordering, in mm. 51 / 76 / 102 are 2in / 3in / 4in. */
  sizesMm: [51, 76, 102],
} as const;

/** The three radii a die-cut circle actually has, for a given cut diameter.
 *  Returned in the units of a box whose side is the full bleed square. */
export function stickerRadii(cutMm: number, box = 240) {
  const total = cutMm + 2 * STICKER.bleedMm;
  const half = box / 2;
  return {
    total,
    box,
    bleed: half,
    cut: half * (cutMm / total),
    safe: half * ((cutMm - 2 * STICKER.safeMm) / total),
  };
}
