/**
 * VIBE CORP — brand root.
 *
 * The single source of truth for the mark, the palette and the type scale.
 * Everything downstream reads from here: the React components in
 * components/brand, the standalone SVGs in /brand (generated by
 * scripts/export-brand.mjs), and eventually the site.
 *
 * The mark is drawn on a 150x150 canvas. It is NOT geometrically perfect —
 * the disc and the inner ring are both slightly irregular, hand-drawn circles,
 * and the whole mark sits about one unit high of centre. That is deliberate
 * and preserved: Vibe Corp is old and accreted, and a mark struck by hand a
 * long time ago should not measure like one struck by a machine. Do not
 * "correct" these paths to true circles.
 */

export const MARK_VIEWBOX = "0 0 150 150";

/** Optical centre of the mark — the disc, ring and waves all agree on this,
 *  and it is NOT (75, 75). Anything concentric with the mark uses this. */
export const MARK_CENTER = { x: 75, y: 74.2 } as const;

/** The outer disc — the black ground the mark is struck into. */
export const DISC_PATH =
  "m143.8 73c-0.5-25.1-15.3-43.2-27.5-52-10.2-7.3-22.3-13-37.2-13.7h-6.1c-13.4 0.3-24.2 4.2-32.9 9.5-8.6 5.3-16.5 12.7-22.3 21.5-5.5 8.5-9.8 18.4-10.8 30.2-0.2 1.8-0.2 3.5-0.4 4.9v3.5c0.4 16 6.1 27.8 12.8 36.9 3.6 4.9 8.4 9.8 14 13.9 10.2 7.3 22.6 13.7 39.3 14.7h3.8c13.8-0.3 24.5-3.7 33.1-8.5 4.6-2.5 8.7-5.4 12.3-8.6l3.9-3.8c8.7-9.4 16-21.8 17.8-38.5 0.2-2 0.4-4 0.4-6.1v-3.9h-0.2z";

/** The inner hairline ring. Stroked, never filled. */
export const RING_PATH =
  "m73.1 25.1c-22.4 0.6-40.6 17.7-46.2 38.4-0.9 4.3-0.9 8.5-0.7 12.8 1.1 18.9 13.9 36.6 33.2 43.3 4.6 1.4 9 2.4 14 2.7 21.2 0.7 38.6-11.1 45.9-27.6 2.6-5.7 4.3-12.4 4.5-19.9 0-20.9-12-36.7-28.2-44.6-5.3-2.7-12.8-5.3-22.5-5.1z";

export const RING_STROKE_WIDTH = 1.7498;

/** The three waves — the glyph proper. Top to bottom. */
export const WAVE_PATHS = [
  "m68.7 34.9c-9.4 0-17.2 5-22.7 11.3-3.8 4.6-8.4 11.7-10.6 20.3-0.4 4 2.4 0.1 7.1-4 3.1-2.7 7.8-5.9 10.2-7.1 3.9-2.1 7.3-3.8 12.9-3.9 5 0.1 10.3 2.1 15.4 8.6 3 4 5.2 6.5 9.3 9 3.7 2.3 7.4 3.6 12.3 2.6 5.2-1.1 9.6-4.4 13.2-7.6 0.5-0.4 0.4-1.1-0.1-4.1-0.5-2.4-0.8-1.8-2.1-1.1-1.7 0.9-3.4 2.2-7.5 2.1-2.1-0.1-5-1.1-7.3-3.4-3.4-3.4-6.2-9.7-10.4-14-4.1-4.4-10-8.5-18.7-8.7h-1z",
  "m61.5 59.2c-6.9 0-13.5 4.1-18.7 8.8-3.1 2.9-4.5 3.9-7.6 5.9-0.7 0.5-0.8 0.6-0.6 4.1 0.3 3.8 0.7 2.2 5.1-1.1 5-3.8 10.2-7.8 18.5-7.9 3.4 0 7.2 1 10.9 3.3 4 2.6 6.3 5.8 8 7.6 3.9 3.9 8.4 6.7 14.4 7h1.6c7.3-0.3 12.3-2.9 18.8-8 3-2.4 4.6-2.8 5.1-3.4 0.3-0.4 0.3-3.9 0-6.2-0.4-1.8-1.9 0.2-4.2 1.9-4 2.9-8.8 6.3-16.3 6.4-4.4 0-10.3-1.5-16-7.3-2.9-3-7.8-10.3-18.3-11.1h-0.7z",
  "m55.4 75.1c-6.2 0.1-10.3 3.2-14 6.2-4 3.1-5.5 4.1-5.7 4.2s-0.1 1.5 0.7 3.9c0.7 1.9 1.2 0.7 3.9-0.5 2.2-1.2 5.4-2.4 8.1-1.8 5.8 1.4 8 5 12.2 11.2 1.8 2.5 4 5.2 6 7.1 5.2 4.7 10.5 7.7 18.3 7.8 5.1-0.1 10.7-1.7 15-4.1 5.9-3.4 10.2-8.5 12.2-12.2 2.4-4 4.2-8.5 4.6-13.1 0.2-3.2-1.5-1.9-4.3 1.1-4 3.5-11 9-20.3 9.3h-1.4c-8.3 0-14-3.6-18.7-9.4-3.9-4.6-7.8-9.3-15.6-9.7h-1z",
];

/** Tight square viewBox around the waves alone, for the bare glyph.
 *  Measured, not guessed: the waves occupy 34.51,34.9 to 117.23,113.2. */
export const GLYPH_VIEWBOX = "32.9 31.1 86 86";

/**
 * PALETTE.
 *
 * Lifted out of the deck, where it was already locked, and given roles. The
 * hex values are unchanged — the cards, the back and the stickers must be the
 * same outfit.
 *
 * `signal` is the one that matters: mustard is Vibe Corp's single signal
 * colour. It marks the thing you are meant to read. Everything else is ground,
 * ink, or band.
 */
export const PALETTE = {
  // Grounds — what brand surfaces sit on.
  black: { hex: "#000000", role: "Deep ground. Cosmic backdrop, sticker die-cut ground." },
  ink: { hex: "#0b0b0c", role: "The disc. Near-black with a hint of warmth." },
  plum: { hex: "#251435", role: "The working ground. Plates, panels, page." },
  // Ink — what sits on the grounds.
  cream: { hex: "#f3e9d6", role: "Body ink on dark. Never pure white." },
  // Signal — the one colour that means 'read this'.
  mustard: { hex: "#e8a929", role: "SIGNAL. Rules, borders, the one true line, the seal's type." },
  // Bands — the wave pattern and illustration. Never used for type.
  teal: { hex: "#2fa090", role: "Band." },
  blue: { hex: "#3358c4", role: "Band." },
  purple: { hex: "#a274d6", role: "Band. Also the uniform — crew hi-vis." },
  rose: { hex: "#dd8296", role: "Band." },
  brick: { hex: "#c4462a", role: "Band." },
} as const;

export type PaletteKey = keyof typeof PALETTE;

export const BAND_KEYS: PaletteKey[] = ["teal", "mustard", "brick", "rose", "purple", "blue"];

/** The gradient treatment — teal to blue to rose, the sweep on the card back.
 *  A TREATMENT, not the mark. The flat mark is canonical. */
export const GRADIENT_STOPS = [
  { offset: "0%", color: PALETTE.teal.hex },
  { offset: "45%", color: PALETTE.blue.hex },
  { offset: "100%", color: PALETTE.rose.hex },
];

/**
 * TYPE — three voices, no more.
 *
 * Already true on the cards; named here so it holds off them too.
 *  PLATE   uppercase, heavily letterspaced sans. Names, labels, headings.
 *  CODE    mono. Classification codes, URLs, anything machine-issued.
 *  TRUE    ornate serif. The one line per surface that is the point.
 */
export const TYPE_VOICES = [
  {
    key: "plate",
    name: "Plate",
    use: "Names, designations, labels, headings, the seal's ring type.",
    css: "uppercase, tracking 0.16–0.2em, semibold",
  },
  {
    key: "code",
    name: "Code",
    use: "Classification codes, URLs, section labels. Anything issued by the Grid rather than written by a person.",
    css: "mono, uppercase, tracking 0.2–0.42em",
  },
  {
    key: "true",
    name: "True",
    use: "The one serif line per surface. Taglines, assignments. Never more than one voice-of-truth block.",
    css: "serif, often uppercase with tracking 0.09em",
  },
] as const;
